### ISSUE TITLE
Support for on demand frame buffer request

### ISSUE THREAD

**Issue by TFTomSun** [qmfrederik/remoteviewing#14]
Hello,
thanks for the effort that you already put into that component. Would you mind to offer the possibility to do the communication manual without a always running thread? 

Background: I don't want to poll all the time for image updates and cut the regions of interest. I would like to get frames on demand of specific regions.
What would be necessary:
- possibility to suppress the start of the polling thread
public access to Functions like:
SendFrameBufferUpdateRequest (incl. the possibility to pass the rectangle that is of interest)
HandleFrameBufferUpdate which returns the image data of the requested region

or better, one function that does that all in a synchronous way:

byte[] LoadFrameBufferRectangle(Rectangle boundsOfInterest)

Best regards, Tom

**Comment by qmfrederik** [comment]
Hi Tom,

Sure, I don't see why this couldn't be done. If you have a PR for this, I'd be happy to review it.

**Comment by qmfrederik** [comment]
Hi @TFTomSun,

Can we close this now #15 got merged?

**Comment by TFTomSun** [comment]
sure. thank you!
