### ISSUE TITLE
Can I use in UWP windows 10?

### ISSUE THREAD

**Issue by jocinei** [qmfrederik/remoteviewing#4]
I need a remote control , like teamviwer in my application.  I want to try your component , it's possible?

**Comment by qmfrederik** [comment]
Do you want to remotely control the phone on which your application is running (as a server), or do you want to use the application on UWP to remotely control another computer (so the phone works as a client)?

**Comment by qmfrederik** [comment]
I'm going to close this as I haven't had a response in a while, feel free to reopen.
