### ISSUE TITLE
Cannot compile in VS2015

### ISSUE THREAD

**Issue by johnnyontheweb** [qmfrederik/remoteviewing#5]
I'm trying to compile this interesting project in VS2015 Community, but I cannot do it since the project RemoteViewing.Windows.Forms cannot compile, it says the RemoteViewing DLL is missing, but it is correctly referenced. 
I've already tried to reference again the DLL file directly or the RemoteViewing project, nothing changes.
Any clue on that?

**Comment by ljruiten** [comment]
Did you check if all projects are set to build in the configuration manager?

**Comment by qmfrederik** [comment]
@johnnyontheweb There was an issue where RemoteViewing was built for .NET 4.5, but the other projects were built for .NET 4.0.

It should be fixed on master now - the AppVeyor builds are green https://ci.appveyor.com/project/qmfrederik/remoteviewing

**Comment by johnnyontheweb** [comment]
Thanks, it's working now!
