### ISSUE TITLE
Multiple clients at once

### ISSUE THREAD

**Issue by ljruiten** [qmfrederik/remoteviewing#6]
Hi,

Does this library support multiple clients connected at the same time, and if so, what is the correct way to do it?
Is it the Session.Connect() function that has to be started on a newly spawned thread for each new incoming client? That is more or less the way I tried to do it yesterday, but that did not seem to work. I can provide the code if necessary, but I was mainly wondering if this is possible at all with this libary.

Kind regards,
LJ

**Comment by qmfrederik** [comment]
I don't see why it shouldn't work, but it's not something I've tried.

**Comment by ljruiten** [comment]
I'll give it another go tomorrow and let you know. What happened was that as soon as the second client connected, the screen of the first one froze.

**Comment by qmfrederik** [comment]
Oh, that sounds like something which could happen. I guess there may be an event loop which dispatches its updates to the most recent client, instead of all connected clients.

**Comment by ljruiten** [comment]
Yes I was not sure how to deal with the Application.Run() that starts the message loop. I have a fork of this repository which I will try to update with my attempt at multiple clients at once.

**Comment by ljruiten** [comment]
Not sure why it did not work before, but with the following code, multiple clients can be connected at the same time.

Should this be the ServerExample or do you prefer it as it is? 

Anyway this issue should be closed.

```csharp
class Program
{
    static string Password = "test";
    static VncServerSession Session;

    static void HandleConnected(object sender, EventArgs e)
    {
        Console.WriteLine("Connected");
    }

    static void HandleConnectionFailed(object sender, EventArgs e)
    {
        Console.WriteLine("Connection Failed");
    }

    static void HandleClosed(object sender, EventArgs e)
    {
        Console.WriteLine("Closed");
    }

    static void HandlePasswordProvided(object sender, PasswordProvidedEventArgs e)
    {
        e.Accept(Password.ToCharArray());
    }

    [STAThread]
    static void Main(string[] args)
    {
        Console.WriteLine("Listening on local port 5900.");
        Console.WriteLine("Try to connect! The password is: {0}", Password);

        var listener = new TcpListener(IPAddress.Any, 5900);
        listener.Start();

        while (true)
        {
            var client = listener.AcceptTcpClient();

            ThreadPool.QueueUserWorkItem((c) => CreateSession(client));
        }
    }

    static void CreateSession(TcpClient client) 
    {
        // Set up a framebuffer and options.
        var options = new VncServerSessionOptions();
        options.AuthenticationMethod = AuthenticationMethod.Password;

        // Virtual mouse
        var mouse = new VncMouse();

        // Create a session.
        Session = new VncServerSession();
        Session.Connected += HandleConnected;
        Session.ConnectionFailed += HandleConnectionFailed;
        Session.Closed += HandleClosed;
        Session.PasswordProvided += HandlePasswordProvided;
        Session.SetFramebufferSource(new VncScreenFramebufferSource("Hello World", Screen.PrimaryScreen));
        //Session.PointerChanged += mouse.OnMouseUpdate;
        Session.Connect(client.GetStream(), options);

        Application.Run();
    }
}
`

**Comment by qmfrederik** [comment]
@ljruiten feel free to send a PR which updates the example if you want, I'll accept it :)

There have been some changes in master today, so you'll probably want to pull in my changes first.

**Comment by qmfrederik** [comment]
Closing as I think the issue has been answered.
